version: '2'
services:
    configuration-server:
        build: .
        container_name: "configuration-server"
        network_mode: "host"
        restart: always
        environment:
            SPRING_CLOUD_CONSUL_HOST: 192.168.1.227
            JVM_HEAP_MAX: 768m
            JVM_JMX_HOST: 127.0.0.1
            JVM_JMX_PORT: 1999
